language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr
#  - jimhester/lintr

after_success:
  #- Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
